<section class="section contentLeft" id="becomeCustomers">
	<div class="row">
		<div class="small-10 small-centered medium-8 medium-offset-1 large-7 large-offset-1 end columns sectionDescription">
			<h2 class="sectionTitle">Prospects turn into customers</h2>
			<p>This is why you hired us right? When prospects become customers they also become customers for other insurance products that you offer such as auto, umbrella, life, commercial and even financial services. They usually become good referral sources, too. We think you'll do better, but even if only one prospect turns into an 8-year client, this single conversion covers the costs of our services each month.</p>
			<a class="button" href="#pricing">Let's get started!</a>
		</div>
	</div>
</section>
