<section class="section alt contentLeft" id="dataScrubbing">
	<div class="contentSection row">
		<div class="small-10 small-centered medium-5 medium-uncentered medium-offset-1 large-5 columns sectionDescription">
			<h2 class="sectionTitle">Data scrubbing</h2>
			<p>Prior to print production we recommend that you remove existing clients that are insured with your company.  Most carriers even require this.  After all, why waste your money sending quotes to your existing customer base?  Spare the embarrassment and save more money!</p>
		</div>
		<div class="small-10 small-centered medium-5 medium-uncentered medium-offset-0 large-4 large-offset-1 columns scrubImage end">
			<?php include('dataScrubbingAnim.inc'); ?>
		</div>
	</div>
</section>
