<section class="section alt contentLeft" id="howItWorks">
	<h1 class="sectionTitle">How it works</h1>
	<div class="row">
		<div class="small-10 small-centered large-uncentered large-offset-1  large-5 columns sectionDescription">
			<h3 class="sectionSubTitleAlt">Signing up</h3>
			<p>When you sign up, we’ll provide you with our digital Getting Started Kit. In the kit, you will find our exclusive HQ Foundation Matrix, which you will fill out with mock premiums for homes with certain year-built and square-foot intervals for the zip codes in which you are marketing. You will also provide the average cost-per square-foot to rebuild homes in your sales area.</p>

			<h4 class="sectionSubTitle">Big experience to help guide you</h4>
			<p>With decades of experience in the home insurance industry, our fully licensed insurance executives will personally review your mock premiums and help you make any adjustments necessary and answer any questions during this process.</p>
		</div>
		<div class="small-hide small-10 small-centered large-uncentered large-6 end columns">
			<div class="hqMatrixContainer">
				<div class="hqMatrix">
					<div class="screen">
						<div class="mockSuccess">
							<img src="images/matrix/quotesComplete.svg">
						</div>

						<div class="topBar">
							<img src="images/matrix/hqLogo.svg" class="hqLogo">
							<table class="topInputs">
								<tr>
									<td valign="top" class="left">
										<table>
											<tr>
												<td class="mockInputLabel">Zip Codes</td>
												<td class="mockValueInput"><span class="topInput zipCodes"></span><span class="ph">|</span></td>
											</tr>
											<tr>
												<td class="mockInputLabel">Deductible</td>
												<td class="mockValueInput"><span class="topInput deductible"></span><span class="ph">|</span></td>
											</tr>
											<tr>
												<td class="mockInputLabel">Dwelling</td>
												<td class="mockValueInput"><span class="topInput dwelling"></span><span class="ph">|</span><span class="sub">($ / sq. ft)</span></td>
											</tr>
										</table>
									</td>
									<td valign="top">
										<table>
											<tr>
												<td class="mockInputLabel">Separate Structures</td>
												<td class="mockValueInput"><span class="topInput sepStructure"></span><span class="ph">|</span></td>
											</tr>
											<tr>
												<td class="mockInputLabel">Personal Property</td>
												<td class="mockValueInput"><span class="topInput personalProperty"></span><span class="ph">|</span></td>
											</tr>
										</table>
									</td>
								</tr>
							</table>

						</div>
						<div class="mockControls">
							<div class="mockContainer">
								<div class="mockItems">
									<span class="mockTitle">Square Feet <span class="mockSquareFeet">1,000</span></span>
									<div class="mockRow">
										<span class="mockLabel">Dwelling</span>
										<span class="mockValue mockDwelling hidden">$125,000</span>
									</div>
									<div class="mockRow">
										<span class="mockLabel">Separate Structure</span>
										<span class="mockValue mockSepStructure hidden">$12,500</span>
									</div>
									<div class="mockRow">
										<span class="mockLabel">Personal Property</span>
										<span class="mockValue mockPersonalProperty hidden">$93,750</span>
									</div>
									<div class="mockRow">
										<span class="mockLabel">Loss of Use</span>
										<span class="mockValue mockLossOfUse">Up to 12 months</span>
									</div>
									<div class="mockRow">
										<span class="mockLabel">Liability</span>
										<span class="mockValue mockLiability">$300,000</span>
									</div>
									<div class="mockRow">
										<span class="mockLabel">Guest Medical</span>
										<span class="mockValue mockMedical">$5,000</span>
									</div>
								</div>
								<div class="dots">
									<div class="dot active"></div>
									<div class="dot"></div>
									<div class="dot"></div>
									<div class="dot"></div>
									<div class="dot"></div>
									<div class="dot"></div>
									<div class="dot"></div>
									<div class="dot"></div>
								</div>
							</div>
							<div class="mockSidebar">
								<span class="mockTitle">Estimated  Premiums</span>
								<div>
									<span class="mockLabel"><?php echo date('Y'); ?></span>
									<span class="mockValue"><span class="value premium"></span><span class="ph">|</span></span>
								</div>
								<div>
									<span class="mockLabel">2010</span>
									<span class="mockValue"><span class="value premium"></span><span class="ph">|</span></span>
								</div>
								<div>
									<span class="mockLabel">2000</span>
									<span class="mockValue"><span class="value premium"></span><span class="ph">|</span></span>
								</div>
								<div>
									<span class="mockLabel">1990</span>
									<span class="mockValue"><span class="value premium"></span><span class="ph">|</span></span>
								</div>
								<div>
									<span class="mockLabel">1975</span>
									<span class="mockValue"><span class="value premium"></span><span class="ph">|</span></span>
								</div>

								<div class="next">NEXT</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
