<section class="section process">
	<h1 class="sectionTitle">Reach the right audience with the right message</h1>
	<div class="row">
		<div class="medium-12 small-12 small-centered columns">
			<div class="medium-4 columns processStep targeting">
				<img src="images/icon_targeting.png" class="processIcon xsmall-hide">
				<h3 class="processTitle">The most advanced targeting</h3>
				<p class="processDescription">We'll help you identify your ideal target audience based on where your carrier is the most competitive, so that you’re only marketing to prospects most likely to buy your insurance.</p>
			</div>
			<div class="medium-4 columns processStep quotes">
				<img src="images/icon_accurateQuotes.png" class="processIcon xsmall-hide">
				<h3 class="processTitle">Accurate customized quotes</h3>
				<p class="processDescription">For each matching home, our custom-built software program (which we've nick-named "HQ") intelligently generates accurate quotes based on each prospect's home's year built, square feet and replacement cost using your carrier's discounts and pricing.</p>
			</div>
			<div class="medium-4 columns processStep templates">
				<img src="images/icon_provenTemplates.png" class="processIcon xsmall-hide">
				<h3 class="processTitle">Proven templates</h3>
				<p class="processDescription">Your quotes are printed on a proven, customized template of your choosing, which also effectively displays your agency's contact information. We'll mail them so they arrive in the mailbox approximately 30-45 days before each prospect's specific home insurance renewal date.
				</p>
			</div>
		</div>
	</div>
</section>
