<section class="section recap" id="recap">
	<h4 class="sectionSubTitle">Better ROI using big data and personalization</h4>
	<div class="row">
		<div class="medium-1 medium-offset-1 columns iconContainer">
			<img src="images/icon_targeting_sm.png" class="processIcon">
		</div>
		<div class="medium-4 columns recapDescription">
			<h3 class="processTitle">Targeting the right homes at the right time</h3>
			<p class="processDescription">We won't waste your money mailing out hundreds or thousands of generic "one size fits all" quotes to every home in a zip code. Instead we use advanced computer modeling to mail individualized and personalized accurate quotes to homes that are within 30-45 days of insurance renewal and where your rates are most competitive ensuring the best possible ROI for your agency.</p>

			<p class="processDescription">The consumer data we use in your direct mail campaigns is obtained from the largest data vendor on the globe. It is absolutely the cleanest and most accurate data available anywhere.</p>
		</div>
		<div class="medium-1 columns iconContainer">
			<img src="images/icon_accurateQuotes_sm.png" class="processIcon">
		</div>
		<div class="medium-4 columns end recapDescription">
			<h3 class="processTitle">Personalized accurate quotes</h3>
			<p class="processDescription">Prospects are much more likely to respond to an individualized and customized letter rather than a generic direct mail advertisement. But personalization is more than just putting a prospect's name on a quote. Our quotes also contain the prospect’s specific home data including square footage and year built. In addition, our program also uses your carrier's premiums to generate personalized and accurate insurance quotes for every targeted home in the sales area of your choice.</p>
		</div>
	</div>

	<h4 class="sectionSubTitle">Exclusive and completely turn-key</h4>
	<div class="row">
		<div class="medium-1 medium-offset-1 columns iconContainer">
			<img src="images/icon_exclusive_sm.png" class="processIcon">
		</div>
		<div class="medium-4 columns recapDescription">
			<h3 class="processTitle">Exclusively yours</h3>
			<p class="processDescription">When we say that we want you to write more policies and get the best ROI possible, we mean it. One of the ways we help to ensure this is to give every agency a first-come, first-serve exclusive right to its preferred target zip codes. That means no other agents will be competing against you using our service.</p>
		</div>
		<div class="medium-1 columns iconContainer">
			<img src="images/icon_handleMail_sm.png" class="processIcon">
		</div>
		<div class="medium-4 columns end recapDescription">
			<h3 class="processTitle">You handle the policies. We’ll handle the mail.</h3>
			<p class="processDescription">Spend your time writing policies, not creating marketing content and paying your staff to manage a direct mail marketing program. We provide data acquisition, spot-on accurate quotes, proven customizable templates, professional printing, folding, inserting, sealing, postage and mailing via USPS.</p>
		</div>
	</div>
</section>
