<section class="section contentRight" id="targetedProspects">
	<div class="contentSection row">
		<div class="small-hide small-10 small-centered medium-5 medium-uncentered large-offset-1 large-5 columns prospectsImgContainer">
			<div class="prospectsImg">
				<div class="viewer">
					<img src="data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="  data-src="images/targetedProspects/hq.png" class="hq lazy">
					<div class="ring"></div>
					<div class="ring"></div>
					<div class="ring"></div>
					<div class="ring"></div>
					<div class="ring"></div>
					<div class="home"></div>
				</div>
				<div class="hqQuote">$726.11</div>
			</div>
		</div>
		<div class="small-10 small-centered medium-uncentered medium-6 large-5 small-offset-1 medium-offset-0 end columns sectionDescription">
			<h2 class="sectionTitle">Your choice of targeted prospects + your mock premiums</h2>
			<p>After you sign up, we'll input your mock premiums into HQ, our custom-built software program that intelligently uses sophisticated algorithms to generate accurate quotes for each of your targeted prospects by the hundreds or thousands.</p>
		</div>
	</div>
</section>
