<nav class="mainMenu">
	<div class="row">
		<div class="small-6 medium-3 medium-offset-1 columns logoContainer">
			<img src="images/headerLogo.svg" class="headerLogo">
		</div>
		<div class="small-6 medium-7 end columns navContainer">
			<ul class="nav-collapse inline-list nav">
				<li class="menuItem scroller"><a href="index.php?#ourService">Our Service</a></li>
				<li class="menuItem scroller"><a href="index.php?#howItWorks">How it Works</a></li>
				<li class="menuItem scroller"><a href="index.php?#templates">Templates</a></li>
				<li class="menuItem scroller"><a href="index.php?#pricing">Pricing</a></li>
				<li class="menuItem"><a href="about.php">About Us</a></li>
				<li class="menuItem getStartedItem scroller"><a class="getStarted" href="index.php?#contact">Get Started!</a></li>
			</ul>
			<div class="menuIcon"></div>
		</div>
	</div>
</nav>
