<style>
	.styled-underline {
		margin: 0;
		display: inline-block;
		position: relative;
	}
	.styled-underline:after {
	  content: '';
	  position: absolute;
	  display: block;
	  height: .25em;
	  width: 120%;
	  margin-left: -60%;
	  left: 50%;
	  bottom: -.1em;
	  border-radius: 50%;
	  z-index: 1;
	  background: #efefef;
	}
	.styled-underline:before {
	content: '';
	  position: absolute;
	  display: block;
	  height: .22em;
	  width: 110%;
	  margin-left: -55%;
	  left: 50%;
	  bottom: -.02em;
	  border-radius: 50%;
	  z-index: 10;
	  background: white;
	  background: linear-gradient(to right, red 25%,white 100%);
	}
</style>
<div class="section ">
	<!-- <h3 class="sectionTitle">WORD IS GETTING OUT.&nbsp;&nbsp;&nbsp;TRUSTED BY AGENTS AT COMPANIES LIKE…</h3> -->
	<div class="row">
        <div class="sectionTitle" style="font-size:22px">
	        <h2 style="font-weight:600">HomeView<span style="font-weight:300">&trade;</span> makes it personal.</h2>
	        That's why prospects who receive your competitive home quote with a photo of their <em class="styled-underline">actual house</em> are more likely to drop
their current insurance carrier and choose <span style="font-weight:800">YOUR agency instead.</span></div>
    </div>
</div>

<div class="section trusted">
	<h3 class="sectionTitle">WORD IS GETTING OUT.&nbsp;&nbsp;&nbsp;TRUSTED BY AGENTS AT COMPANIES LIKE…</h3>
	<div class="row">
		<div class="trustedBy small-12 medium-11 medium-centered large-10 columns"></div>
	</div>
</div>
